const questions = [
    "Em quantos dias Deus criou o mundo?",
    "Em qual dia Jesus nasceu?",
    "Qual o nome da Mãe de Jesus?",
    "O que é o pecado?",
    "Qual oração Jesus ensinou aos seus discípulos?",
    "Qual a diferença entre orar e rezar?",
    "Em que dia foi instituída a Eucaristia?",
    "Qual dia não devemos faltar à missa?",
    "Quem pode ser santo?",
    "Se pecamos mortalmente, o que devemos fazer para recuperar a graça?",
    "Como se chama o o pecado de Adão e Eva?",
    "Quantos eram os apóstolos de Jesus?",
    "Qual foi o primeiro milagre de Jesus?",
    "Quantos são os evangelhos?",
    "Quando começa a Quaresma?",
    "Quais são os três pilares da Quaresma?",
    "Qual o dia da semana na quaresma que obrigatoriamente não se come carne?",
    "Quem é a primeira pessoa da Santíssima Trindade?",
    "Onde Jesus nasceu?",
    "Qual o meio para criar intimidade com Deus?",
    "Qual a ordem dos evangelhos de acordo com a Bíblia?",
    "Quantos dias tem a quaresma?",
    "De que maneiras podemos orar?",
    "Qual o significado do sábado de aleluia?",
    "O que significa ser batizado?",
    "O que é a confissão?",
    "Qual é o maior mandamento?",
    "Quantos anos Jesus tinha quando começou sua vida pública?",
];
const doubtFaith = [
    "O que aconteceu três dias após a morte de Jesus?",
    "Como sabemos quando é pecado venial e quando é pecado mortal?",
    "Quem foi o primeiro Papa?",
    "Qual apóstolo negou Jesus três vezes?",
    "Qual o nome dos pais de Maria?",
    "Qual o nome do anjo que anunciou a Maria que ela seria a mãe de Jesus?",
    "Quando Maria recebeu o Espírito Santo?",
    "O que é a ascensão de Jesus?",
    "Para que Jesus se entregou à morte?",
    "Quais são as características de Deus Pai?",
    "O que é a conversão?",
    "O que é a fé?",
    "Qual o dia da semana santa onde refletimos com salmos de lamentação?",
    "Qual o único dia do ano que não se celebra a missa?",
    "Em que ano litúrgico estamos? A, B ou C?",
    "O que é a oração?",
    "Quantos anos durou a vida pública de Jesus?",
    "Qual era a profissão de Jesus antes de iniciar sua vida pública?",
    "Quais são os dois maiores mandamentos que Jesus nos deixou?",
];  

export { questions, doubtFaith };